from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet,
    FriendViewSet,
    ChatRoomViewSet,
    ChatMessageViewSet,
    PongGameViewSet,
    TicTacToeGameViewSet,
    LeaderboardViewSet,
    BlockedUserViewSet,
)

# Create a router and register your viewsets
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'friends', FriendViewSet)
router.register(r'chat-rooms', ChatRoomViewSet)
router.register(r'chat-messages', ChatMessageViewSet)
router.register(r'pong-games', PongGameViewSet)
router.register(r'tictactoe-games', TicTacToeGameViewSet)
router.register(r'leaderboard', LeaderboardViewSet)
router.register(r'blocked-users', BlockedUserViewSet)

# Define the URL patterns
urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
]
