services:
  backend:
    image: ft_transcendence_backend
    restart: always
    env_file:
      - example.env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ENVIRONMENT=production
    build:
      context: ./dockers/django
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
    networks:
      - backend
      - database

  postgres:
    image: postgres
    restart: always
    env_file:
      - example.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dockers/postgres/conf/50-server.cnf:/etc/postgresql/postgresql.conf
    networks:
      - database

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=table
    networks:
      - database
    depends_on:
      - postgres
    ports:
      - 9000:8080
  nginx:
    build:
      context: ./dockers/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    

volumes:
  postgres_data:
  avatar:

networks:
  frontend:
  backend:
  database:
