version: '3.3'

services:
  backend:
    container_name: ft_transcendence-backend
    image: ft_transcendence_backend
    build:
      context: .
      dockerfile: ./dockers/django/Dockerfile
    restart: unless-stopped
    env_file:
      - ./dockers/.env.dev
    volumes:
      - "./backend:/app/src"
      - "locale_volume:/app/src/locale"
      - "./backend/fixtures:/app/fixtures"
    ports:
      - "4000:8000"
    depends_on:
      - postgres
    networks:
      - ft_transcendence_network

  postgres:
    container_name: ft_transcendence-postgres
    image: ft_transcendence_postgres
    build:
      context: .
      dockerfile: ./dockers/postgres/Dockerfile
    restart: unless-stopped
    env_file:
      - ./dockers/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dockers/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - ft_transcendence_network

  nginx:
    container_name: ft_transcendence-nginx
    image: ft_transcendence_nginx
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    env_file:
      - ./dockers/.env.dev
    restart: unless-stopped
    ports:
      - "8443:443"
    volumes:
      - ./dockers/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ft_transcendence_network

  redis:
    container_name: ft_transcendence-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - ft_transcendence_network

volumes:
  postgres_data:
  locale_volume:

networks:
  ft_transcendence_network:
    external: true
