version: latest



services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: 
  #     dockerfile: 
  #   volumes:
  #   depends_on:
  #   ports:
  #   networks:
  #   restart:
  #   env_file:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/usr/share/nginx/html
    # depends_on: backend
    ports: 
      - "8080:80"
    networks: 
      - ft_transcendence
    restart: on-failure:5

networks:
  ft_transcendence:
    driver: bridge

# pour tester: http://localhost:8080/