version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: ./dockers/django/Dockerfile
    restart: unless-stopped
    env_file:
      - ./dockers/.env.dev
    volumes:
      - "${PROJECT_PATH}/backend:/app/backend"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
    networks:
      - ft_transcendence_network

  postgres:
    image: ft_transcendence_postgres
    build:
      context: .
      dockerfile: ./dockers/postgres/Dockerfile
    restart: unless-stopped
    env_file:
      - ./dockers/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dockers/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - ft_transcendence_network

  nginx:
    image: ft_transcendence_nginx
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    env_file:
      - ./dockers/.env.dev
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./dockers/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ft_transcendence_network

volumes:
  postgres_data:

networks:
  ft_transcendence_network:
