services:
  backend:
    build:
      context: ./django
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - postgres_data_dev:/home/postgres/pgdata
      - ./postgres/50-server.cnf:/etc/postgresql/postgresql.conf
    networks:
      - database

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

volumes:
  postgres_data_dev:

networks:
  backend:
  database:
  frontend:
