version: '3.3'

services:
  backend:
    image: ft_transcendence_backend
    build:
      context: ..
      dockerfile: dockers/django/Dockerfile
    env_file:
      - .env.dev
    volumes:
      - "../backend:/app/src"
    depends_on:
      - postgres
    ports:
      - "5000:8000"
    networks:
      - ft_transcendence_network

  postgres:
    image: ft_transcendence_postgres
    build:
      context: ..
      dockerfile: dockers/postgres/Dockerfile
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ../dockers/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - ft_transcendence_network

  nginx:
    image: ft_transcendence_nginx
    build:
      context: ..
      dockerfile: dockers/nginx/Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../dockers/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - backend
    networks:
      - ft_transcendence_network

volumes:
  postgres_data_dev:

networks:
  ft_transcendence_network:
    driver: bridge
