services:
  backend:
    build:
      context: ..
      dockerfile: dockers/django/Dockerfile
    env_file:
      - ../dockers/.env.dev
    volumes:
      - "${PROJECT_PATH}/backend:/app/backend"
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - ft_transcendence_network

  postgres:
    image: ft_transcendence_postgres
    build:
      context: ..
      dockerfile: dockers/postgres/Dockerfile
    env_file:
      - ../dockers/.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ../dockers/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - ft_transcendence_network

  nginx:
    image: ft_transcendence_nginx
    build:
      context: ..
      dockerfile: dockers/nginx/Dockerfile
    env_file:
      - ../dockers/.env.dev
    volumes:
      - ../dockers/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    networks:
      - ft_transcendence_network

volumes:
  postgres_data_dev:

networks:
  ft_transcendence_network:
    driver: bridge
