services:
  postgres:
    build:
      context: ./dockers/postgres
      dockerfile: Dockerfile
    env_file:
      - ../dockers/dev.env
    ports:
      - "8000:8000"
    environment:
      - PGDATA=/home/postgres/pgdata
    volumes:
      - postgres_data_dev:/home/postgres/pgdata
      - ./dockers/postgres/conf/50-server.cnf:/etc/postgresql/postgresql.conf

volumes:
  postgres_data_dev:
