services:
  backend:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
    networks:
      - backend

  postgres:
    image: ft_transcendence_postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - postgres_data_dev:/home/postgres/pgdata
      - ./postgres/50-server.cnf:/etc/postgresql/postgresql.conf
    networks:
      - database

  nginx:
    image: ft_transcendence_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

volumes:
  postgres_data_dev:

networks:
  backend:
  database:
  frontend:
