version: latest

services:
  backend:
    postgresql:
      image: postgresql
      container_name: postgresql
      build:
        context: ./dockers/postgresql
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - postgresql:/var/lib/postgresql
      expose:
        - "3306"
      restart: unless-stopped
      networks:
        - ft_transcendence
      healthcheck:
        test: myadmin ping --host=localhost -p${PSQL_ROOT_PASSWD};
        interval: 5s
        timeout:  1s
        retries: 10
        start_period: 5s

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/usr/share/nginx/html
    depends_on:
      backend:
        postgresql: service_healthy
    ports: 
      - "8080:80"
    networks: 
      - ft_transcendence
    restart: on-failure:5

volumes:
  postgresql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jubaldo/data/postgresql'

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge